export const MODULES = [
  "Dashboard",
  "Leads",
  "Customers",
  "Pipeline",
  "Quotes",
  "Jobs",
  "Vendors",
  "Purchase Orders",
  "Crew",
  "Dispatch",
  "Calendar",
  "Inventory",
  "Billing",
  "Invoices",
  "Reports",
  "Messages",
  "Notifications",
  "AI Assistant",
  "Profile",
  "Change Password",
  "Team",
  "Settings",
  "Company",
  "Organization",
  "Branding",
  "Invitations",
  "Roles & Permissions",
  "Integrations",
  "AI Settings",
  "Email Templates",
] as const;

export type ModuleName = typeof MODULES[number];