import Link from "next/link";
import { redirect, notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import {
  Prisma,
  SubscriptionPlan,
  SubscriptionStatus,
} from "@prisma/client";

import { auth } from "@/auth";
import prisma from "@/shared/lib/prisma";

export const dynamic = "force-dynamic";

/* =========================================================
   TYPES
   ========================================================= */

type PageProps = {
  params: Promise<{
    id: string;
  }>;
  searchParams?: Promise<{
    subscription?: string;
    subscriptionError?: string;
  }>;
};

/* =========================================================
   PLATFORM AUTHORIZATION
   ========================================================= */

async function requireSuperAdmin() {
  const session = await auth();

  if (!session?.user) {
    redirect("/login");
  }

  const user = session.user as {
    role?: unknown;
  };

  const role = String(user.role ?? "")
    .trim()
    .toLowerCase();

  if (role !== "super_admin") {
    redirect("/admin/dashboard");
  }

  return session;
}

/* =========================================================
   FORM HELPERS
   ========================================================= */

function getString(
  formData: FormData,
  key: string
) {
  return String(
    formData.get(key) ?? ""
  ).trim();
}

function getBoolean(
  formData: FormData,
  key: string
) {
  const value = formData.get(key);

  return (
    value === "true" ||
    value === "1" ||
    value === "on"
  );
}

/* =========================================================
   DURATION
   ========================================================= */

type DurationUnit =
  | "minutes"
  | "hours"
  | "days"
  | "months";

type ParsedDuration = {
  value: number;
  unit: DurationUnit;
};

/**
 * Accepts the values generated by our form:
 *
 * 15m
 * 30m
 * 1h
 * 2h
 * 6h
 * 12h
 * 1d
 * 2d
 * 3d
 * 7d
 * 15d
 * 30d
 * 1mo
 * 3mo
 * 6mo
 * 12mo
 * 24mo
 *
 * Also accepts friendly values such as:
 *
 * 1 month
 * 1 Month
 * 30 days
 *
 * This prevents the old exact-switch failure.
 */
function parseDuration(
  rawValue: string
): ParsedDuration {
  const value = rawValue
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");

  const aliases: Record<
    string,
    ParsedDuration
  > = {
    "15m": {
      value: 15,
      unit: "minutes",
    },

    "30m": {
      value: 30,
      unit: "minutes",
    },

    "1h": {
      value: 1,
      unit: "hours",
    },

    "2h": {
      value: 2,
      unit: "hours",
    },

    "6h": {
      value: 6,
      unit: "hours",
    },

    "12h": {
      value: 12,
      unit: "hours",
    },

    "1d": {
      value: 1,
      unit: "days",
    },

    "2d": {
      value: 2,
      unit: "days",
    },

    "3d": {
      value: 3,
      unit: "days",
    },

    "7d": {
      value: 7,
      unit: "days",
    },

    "15d": {
      value: 15,
      unit: "days",
    },

    "30d": {
      value: 30,
      unit: "days",
    },

    "1mo": {
      value: 1,
      unit: "months",
    },

    "3mo": {
      value: 3,
      unit: "months",
    },

    "6mo": {
      value: 6,
      unit: "months",
    },

    "12mo": {
      value: 12,
      unit: "months",
    },

    "24mo": {
      value: 24,
      unit: "months",
    },

    "15 minutes": {
      value: 15,
      unit: "minutes",
    },

    "30 minutes": {
      value: 30,
      unit: "minutes",
    },

    "1 hour": {
      value: 1,
      unit: "hours",
    },

    "2 hours": {
      value: 2,
      unit: "hours",
    },

    "6 hours": {
      value: 6,
      unit: "hours",
    },

    "12 hours": {
      value: 12,
      unit: "hours",
    },

    "1 day": {
      value: 1,
      unit: "days",
    },

    "2 days": {
      value: 2,
      unit: "days",
    },

    "3 days": {
      value: 3,
      unit: "days",
    },

    "7 days": {
      value: 7,
      unit: "days",
    },

    "15 days": {
      value: 15,
      unit: "days",
    },

    "30 days": {
      value: 30,
      unit: "days",
    },

    "1 month": {
      value: 1,
      unit: "months",
    },

    "3 months": {
      value: 3,
      unit: "months",
    },

    "6 months": {
      value: 6,
      unit: "months",
    },

    "12 months": {
      value: 12,
      unit: "months",
    },

    "24 months": {
      value: 24,
      unit: "months",
    },
  };

  const parsed = aliases[value];

  if (!parsed) {
    throw new Error(
      `Invalid subscription duration: ${rawValue || "empty"}`
    );
  }

  return parsed;
}

/* =========================================================
   DATE HELPERS
   ========================================================= */

/**
 * Adds months without allowing dates such as Jan 31
 * to unexpectedly jump two months forward.
 */
function addMonthsSafe(
  date: Date,
  months: number
) {
  const result = new Date(date);

  const originalDay =
    result.getDate();

  result.setDate(1);

  result.setMonth(
    result.getMonth() + months
  );

  const lastDayOfMonth =
    new Date(
      result.getFullYear(),
      result.getMonth() + 1,
      0
    ).getDate();

  result.setDate(
    Math.min(
      originalDay,
      lastDayOfMonth
    )
  );

  return result;
}

function calculateExpiry(
  baseDate: Date,
  duration: ParsedDuration
) {
  const result = new Date(baseDate);

  switch (duration.unit) {
    case "minutes":
      result.setMinutes(
        result.getMinutes() +
          duration.value
      );
      break;

    case "hours":
      result.setHours(
        result.getHours() +
          duration.value
      );
      break;

    case "days":
      result.setDate(
        result.getDate() +
          duration.value
      );
      break;

    case "months":
      return addMonthsSafe(
        result,
        duration.value
      );
  }

  return result;
}

/* =========================================================
   SERVER ACTION
   ========================================================= */

async function changeSubscription(
  formData: FormData
) {
  "use server";

  /*
   * IMPORTANT:
   * Never trust the page/middleware alone.
   * Server actions must authorize themselves.
   */
  await requireSuperAdmin();

  const orgId =
    getString(formData, "orgId");

  const planValue =
    getString(formData, "plan");

  const durationValue =
    getString(formData, "duration");

  const startFromNow =
    getBoolean(
      formData,
      "startFromNow"
    );

  if (!orgId) {
    redirect(
      "/admin/organizations?subscriptionError=Organization%20ID%20is%20required"
    );
  }

  /*
   * Validate plan against Prisma enum.
   */
  if (
    !Object.values(
      SubscriptionPlan
    ).includes(
      planValue as SubscriptionPlan
    )
  ) {
    redirect(
      `/admin/organizations/${encodeURIComponent(
        orgId
      )}?subscriptionError=Invalid%20subscription%20plan`
    );
  }

  const plan =
    planValue as SubscriptionPlan;

  /*
   * Parse duration before touching the database.
   */
  let duration: ParsedDuration;

  try {
    duration =
      parseDuration(
        durationValue
      );
  } catch (error) {
    console.error(
      "Subscription duration error:",
      error
    );

    redirect(
      `/admin/organizations/${encodeURIComponent(
        orgId
      )}?subscriptionError=${encodeURIComponent(
        error instanceof Error
          ? error.message
          : "Invalid subscription duration"
      )}`
    );
  }

  /*
   * Load organization + actual plan.
   *
   * The Plan table is now the source of truth for:
   * price
   * user limit
   * storage limit
   * AI credits
   */
  const [organization, planRecord] =
    await Promise.all([
      prisma.organization.findUnique({
        where: {
          id: orgId,
        },
        select: {
          id: true,
          name: true,
          active: true,
          plan: true,
          subscriptionEndsAt: true,
        },
      }),

      prisma.plan.findUnique({
        where: {
          code: plan,
        },
      }),
    ]);

  if (!organization) {
    redirect(
      `/admin/organizations/${encodeURIComponent(
        orgId
      )}?subscriptionError=Organization%20not%20found`
    );
  }

  if (!planRecord) {
    redirect(
      `/admin/organizations/${encodeURIComponent(
        orgId
      )}?subscriptionError=Selected%20plan%20was%20not%20found`
    );
  }

  /*
   * Current time.
   */
  const now = new Date();

  /*
   * If admin explicitly selects "Start from current time",
   * ignore the current expiry.
   *
   * Otherwise:
   * - active subscription -> extend from current expiry
   * - expired/missing -> start from now
   */
  let baseDate: Date;

  if (startFromNow) {
    baseDate = new Date(now);
  } else if (
    organization.subscriptionEndsAt &&
    organization.subscriptionEndsAt > now
  ) {
    baseDate =
      new Date(
        organization.subscriptionEndsAt
      );
  } else {
    baseDate = new Date(now);
  }

  /*
   * Calculate new expiry.
   */
  const expiresAt =
    calculateExpiry(
      baseDate,
      duration
    );

  /*
   * Defensive validation.
   */
  if (
    Number.isNaN(
      expiresAt.getTime()
    ) ||
    expiresAt <= baseDate
  ) {
    redirect(
      `/admin/organizations/${encodeURIComponent(
        orgId
      )}?subscriptionError=Could%20not%20calculate%20subscription%20expiry`
    );
  }

  console.log(
    "[ADMIN SUBSCRIPTION CHANGE]",
    {
      orgId,
      plan,
      duration: durationValue,
      durationParsed: duration,
      startFromNow,
      baseDate,
      expiresAt,
    }
  );

  /*
   * IMPORTANT:
   *
   * Subscription + Organization are updated
   * atomically.
   */
  try {
    await prisma.$transaction(
      async (tx) => {
        /*
         * Create or update the real subscription.
         */
        await tx.subscription.upsert({
          where: {
            orgId,
          },

          create: {
            orgId,

            provider: "admin",

            externalId: null,

            customerId: null,

            plan,

            status:
              SubscriptionStatus.active,

            billingCycle: "monthly",

            amount:
              new Prisma.Decimal(
                planRecord.price
              ),

            currency:
              planRecord.currency ||
              "USD",

            renewAt: expiresAt,

            nextInvoiceDate:
              expiresAt,

            trialStart: null,

            trialEnd: null,

            interval: "month",

            cancelAtPeriodEnd:
              false,

            userLimit:
              planRecord.userLimit,

            storageLimit:
              planRecord.storageLimit,

            aiCredits:
              planRecord.aiCredits,
          },

          update: {
            plan,

            status:
              SubscriptionStatus.active,

            amount:
              new Prisma.Decimal(
                planRecord.price
              ),

            currency:
              planRecord.currency ||
              "USD",

            renewAt: expiresAt,

            nextInvoiceDate:
              expiresAt,

            billingCycle:
              "monthly",

            interval:
              "month",

            cancelAtPeriodEnd:
              false,

            userLimit:
              planRecord.userLimit,

            storageLimit:
              planRecord.storageLimit,

            aiCredits:
              planRecord.aiCredits,
          },
        });

        /*
         * Keep Organization synchronized.
         */
        await tx.organization.update({
          where: {
            id: orgId,
          },

          data: {
            plan,

            active: true,

            usersLimit:
              planRecord.userLimit,

            subscriptionEndsAt:
              expiresAt,
          },
        });
      }
    );
  } catch (error) {
    console.error(
      "[ADMIN SUBSCRIPTION CHANGE FAILED]",
      error
    );

    const message =
      error instanceof Error
        ? error.message
        : "Subscription update failed";

    redirect(
      `/admin/organizations/${encodeURIComponent(
        orgId
      )}?subscriptionError=${encodeURIComponent(
        message
      )}`
    );
  }

  /*
   * Refresh all affected admin pages.
   */
  revalidatePath(
    `/admin/organizations/${orgId}`
  );

  revalidatePath(
    `/admin/organizations/${orgId}/users`
  );

  revalidatePath(
    `/admin/organizations/${orgId}/billing`
  );

  revalidatePath(
    `/admin/organizations`
  );

  revalidatePath(
    "/admin/subscriptions"
  );

  revalidatePath(
    "/admin/dashboard"
  );

  /*
   * Redirect instead of returning a raw server-action
   * response. This prevents the generic "page couldn't load"
   * experience after a successful update.
   */
  redirect(
    `/admin/organizations/${encodeURIComponent(
      orgId
    )}?subscription=success`
  );
}

/* =========================================================
   FORMATTERS
   ========================================================= */

function formatPlan(
  plan: SubscriptionPlan | null | undefined
) {
  if (!plan) {
    return "—";
  }

  switch (plan) {
    case SubscriptionPlan.starter:
      return "Starter";

    case SubscriptionPlan.professional:
      return "Professional";

    case SubscriptionPlan.enterprise:
      return "Enterprise";

    default:
      return String(plan);
  }
}

function formatMoney(
  amount:
    | Prisma.Decimal
    | number
    | null
    | undefined
) {
  if (
    amount === null ||
    amount === undefined
  ) {
    return "$0.00";
  }

  return new Intl.NumberFormat(
    "en-US",
    {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }
  ).format(Number(amount));
}

function formatDate(
  date:
    | Date
    | null
    | undefined
) {
  if (!date) {
    return "No subscription";
  }

  return new Intl.DateTimeFormat(
    "en-US",
    {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }
  ).format(date);
}

function formatLimit(
  value:
    | number
    | null
    | undefined
) {
  if (
    value === null ||
    value === undefined
  ) {
    return "—";
  }

  /*
   * Your current seed/database uses unlimited
   * plans. If represented by -1, display Unlimited.
   */
  if (value < 0) {
    return "Unlimited";
  }

  return value.toLocaleString(
    "en-US"
  );
}

/* =========================================================
   PAGE
   ========================================================= */

export default async function OrganizationPage({
  params,
  searchParams,
}: PageProps) {
  /*
   * Page-level authorization.
   */
  await requireSuperAdmin();

  const { id } =
    await params;

  if (!id) {
    notFound();
  }

  const query =
    searchParams
      ? await searchParams
      : {};

  /*
   * Load organization, users, subscription
   * and all active plans.
   */
  const [organization, plans] =
    await Promise.all([
      prisma.organization.findUnique({
        where: {
          id,
        },

        include: {
          users: {
            orderBy: {
              createdAt: "desc",
            },

            include: {
              organizationRole: true,
            },
          },

          subscriptions: true,
        },
      }),

      prisma.plan.findMany({
        where: {
          active: true,
        },

        orderBy: {
          sortOrder: "asc",
        },
      }),
    ]);

  if (!organization) {
    notFound();
  }

  /*
   * In your schema this relation is named
   * `subscriptions`.
   */
  const subscription =
    organization.subscriptions;

  /*
   * Real subscription expiry is primary.
   * Organization expiry is the legacy fallback.
   */
  const expiryDate =
    subscription?.renewAt ??
    organization.subscriptionEndsAt ??
    null;

  const now =
    new Date();

  const subscriptionActive =
    Boolean(
      subscription &&
        subscription.status ===
          SubscriptionStatus.active &&
        expiryDate &&
        expiryDate > now
    );

  /*
   * Find the current plan record.
   */
  const currentPlanRecord =
    plans.find(
      (item) =>
        item.code ===
        (
          subscription?.plan ??
          organization.plan
        )
    );

  const success =
    query.subscription ===
    "success";

  const errorMessage =
    typeof query.subscriptionError ===
    "string"
      ? query.subscriptionError
      : null;

  return (
    <div className="mx-auto max-w-7xl space-y-8 p-6 md:p-10">

      {/* =====================================================
          HEADER
          ===================================================== */}

      <div className="flex flex-col justify-between gap-6 md:flex-row md:items-start">

        <div>
          <div className="mb-3 text-sm text-slate-500">
            Admin / Organizations /{" "}
            {organization.name}
          </div>

          <h1 className="text-4xl font-bold tracking-tight text-slate-950 md:text-5xl">
            {organization.name}
          </h1>

          <p className="mt-2 text-slate-500">
            {organization.email ??
              "Organization management"}
          </p>
        </div>

        <div className="flex flex-wrap gap-3">

          <Link
            href={`/admin/organizations/${id}/users`}
            className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
          >
            Users
          </Link>

          <Link
            href={`/admin/organizations/${id}/billing`}
            className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
          >
            Billing
          </Link>

          <Link
            href="/admin/organizations"
            className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
          >
            Back
          </Link>

        </div>
      </div>

      {/* =====================================================
          SUCCESS MESSAGE
          ===================================================== */}

      {success && (
        <div className="rounded-2xl border border-green-200 bg-green-50 px-5 py-4">
          <div className="font-semibold text-green-900">
            Subscription updated successfully.
          </div>

          <div className="mt-1 text-sm text-green-700">
            The organization, subscription,
            plan limits and expiry date have
            been synchronized.
          </div>
        </div>
      )}

      {/* =====================================================
          ERROR MESSAGE
          ===================================================== */}

      {errorMessage && (
        <div className="rounded-2xl border border-red-200 bg-red-50 px-5 py-4">
          <div className="font-semibold text-red-900">
            Subscription update failed
          </div>

          <div className="mt-1 break-words text-sm text-red-700">
            {errorMessage}
          </div>
        </div>
      )}

      {/* =====================================================
          SUMMARY
          ===================================================== */}

      <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-5">

        {/* CRM */}

        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
          <p className="text-sm text-slate-500">
            CRM
          </p>

          <h2 className="mt-2 text-2xl font-bold capitalize text-slate-950">
            {String(
              organization.crmType
            )}
          </h2>
        </div>

        {/* PLAN */}

        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
          <p className="text-sm text-slate-500">
            Plan
          </p>

          <h2 className="mt-2 text-2xl font-bold text-slate-950">
            {formatPlan(
              subscription?.plan ??
                organization.plan
            )}
          </h2>

          <p className="mt-2 text-sm text-slate-500">
            {formatMoney(
              subscription?.amount ??
                currentPlanRecord?.price ??
                0
            )}
            /month
          </p>
        </div>

        {/* USERS */}

        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
          <p className="text-sm text-slate-500">
            Users
          </p>

          <h2 className="mt-2 text-2xl font-bold text-slate-950">
            {organization.users.length}
          </h2>

          <p className="mt-2 text-sm text-slate-500">
            Limit:{" "}
            {formatLimit(
              subscription?.userLimit ??
                organization.usersLimit
            )}
          </p>
        </div>

        {/* EXPIRES */}

        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
          <p className="text-sm text-slate-500">
            Renewal / Expiry
          </p>

          <h2 className="mt-2 font-bold text-slate-950">
            {formatDate(
              expiryDate
            )}
          </h2>

          {expiryDate &&
            expiryDate > now && (
              <p className="mt-2 text-sm font-medium text-green-600">
                Active until expiry
              </p>
            )}
        </div>

        {/* STATUS */}

        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
          <p className="text-sm text-slate-500">
            Status
          </p>

          <h2
            className={
              subscriptionActive
                ? "mt-2 font-bold text-green-600"
                : "mt-2 font-bold text-red-600"
            }
          >
            {subscriptionActive
              ? "ACTIVE"
              : "EXPIRED"}
          </h2>

          <p className="mt-2 text-xs capitalize text-slate-500">
            {subscription
              ? String(
                  subscription.status
                )
              : "No subscription"}
          </p>
        </div>

      </div>

      {/* =====================================================
          PLAN CAPABILITIES
          ===================================================== */}

      {currentPlanRecord && (
        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">

          <div className="mb-5">
            <h2 className="text-2xl font-bold text-slate-950">
              Current Plan Limits
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Values currently stored for this
              organization's plan.
            </p>
          </div>

          <div className="grid gap-4 md:grid-cols-4">

            <div className="rounded-2xl bg-slate-50 p-5">
              <p className="text-xs font-medium text-slate-500">
                Monthly Price
              </p>

              <p className="mt-2 text-xl font-bold text-slate-950">
                {formatMoney(
                  currentPlanRecord.price
                )}
              </p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-5">
              <p className="text-xs font-medium text-slate-500">
                Employees
              </p>

              <p className="mt-2 text-xl font-bold text-slate-950">
                {formatLimit(
                  currentPlanRecord.userLimit
                )}
              </p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-5">
              <p className="text-xs font-medium text-slate-500">
                Storage
              </p>

              <p className="mt-2 text-xl font-bold text-slate-950">
                {formatLimit(
                  currentPlanRecord.storageLimit
                )}{" "}
                GB
              </p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-5">
              <p className="text-xs font-medium text-slate-500">
                AI Credits
              </p>

              <p className="mt-2 text-xl font-bold text-slate-950">
                {formatLimit(
                  currentPlanRecord.aiCredits
                )}
              </p>
            </div>

          </div>
        </div>
      )}

      {/* =====================================================
          CHANGE SUBSCRIPTION
          ===================================================== */}

      <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm md:p-8">

        <div className="mb-7">

          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">

            <div>
              <h2 className="text-3xl font-bold text-slate-950">
                {subscription
                  ? "Change Subscription"
                  : "Grant Subscription"}
              </h2>

              <p className="mt-2 text-sm text-slate-500">
                Select a plan and duration.
                This updates the organization's
                real subscription record.
              </p>
            </div>

            <div className="rounded-full bg-blue-50 px-4 py-2 text-xs font-semibold text-blue-700">
              Super Admin
            </div>

          </div>
        </div>

        <form
          action={
            changeSubscription
          }
          className="space-y-6"
        >

          <input
            type="hidden"
            name="orgId"
            value={
              organization.id
            }
          />

          <div className="grid gap-5 md:grid-cols-2">

            {/* PLAN */}

            <div>
              <label
                htmlFor="plan"
                className="mb-2 block text-sm font-semibold text-slate-700"
              >
                Subscription Plan
              </label>

              <select
                id="plan"
                name="plan"
                defaultValue={
                  subscription?.plan ??
                  organization.plan
                }
                required
                className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
              >
                {plans.map(
                  (plan) => (
                    <option
                      key={
                        plan.id
                      }
                      value={
                        plan.code
                      }
                    >
                      {plan.name} —{" "}
                      {formatMoney(
                        plan.price
                      )}
                      /month
                    </option>
                  )
                )}
              </select>
            </div>

            {/* DURATION */}

            <div>
              <label
                htmlFor="duration"
                className="mb-2 block text-sm font-semibold text-slate-700"
              >
                Duration
              </label>

              <select
                id="duration"
                name="duration"
                defaultValue="1mo"
                required
                className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
              >
                <optgroup label="Testing">
                  <option value="15m">
                    15 Minutes
                  </option>

                  <option value="30m">
                    30 Minutes
                  </option>

                  <option value="1h">
                    1 Hour
                  </option>

                  <option value="2h">
                    2 Hours
                  </option>

                  <option value="6h">
                    6 Hours
                  </option>

                  <option value="12h">
                    12 Hours
                  </option>
                </optgroup>

                <optgroup label="Days">
                  <option value="1d">
                    1 Day
                  </option>

                  <option value="2d">
                    2 Days
                  </option>

                  <option value="3d">
                    3 Days
                  </option>

                  <option value="7d">
                    7 Days
                  </option>

                  <option value="15d">
                    15 Days
                  </option>

                  <option value="30d">
                    30 Days
                  </option>
                </optgroup>

                <optgroup label="Months">
                  <option value="1mo">
                    1 Month
                  </option>

                  <option value="3mo">
                    3 Months
                  </option>

                  <option value="6mo">
                    6 Months
                  </option>

                  <option value="12mo">
                    12 Months
                  </option>

                  <option value="24mo">
                    24 Months
                  </option>
                </optgroup>
              </select>
            </div>

          </div>

          {/* =================================================
              START FROM NOW
              ================================================= */}

          <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5">

            <label className="flex cursor-pointer items-start gap-3">

              <input
                id="startFromNow"
                name="startFromNow"
                type="checkbox"
                className="mt-1 h-4 w-4 rounded border-slate-300"
              />

              <span>
                <span className="block text-sm font-semibold text-amber-950">
                  Start from current time
                </span>

                <span className="mt-1 block text-xs leading-5 text-amber-800">
                  Use this for testing or when
                  you want the selected duration
                  to begin immediately. Otherwise,
                  an active subscription will be
                  extended from its existing expiry.
                </span>
              </span>

            </label>

          </div>

          {/* =================================================
              ACTION
              ================================================= */}

          <div className="flex flex-col gap-3 sm:flex-row sm:items-center">

            <button
              type="submit"
              className="rounded-xl bg-green-600 px-8 py-3.5 font-semibold text-white shadow-sm transition hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
            >
              {subscription
                ? "Change Plan"
                : "Grant Access"}
            </button>

            <p className="text-xs text-slate-500">
              Changes are applied immediately.
            </p>

          </div>

        </form>

        {/* ===================================================
            CURRENT SUBSCRIPTION
            =================================================== */}

        {subscription && (
          <div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-6">

            <h3 className="mb-5 text-lg font-bold text-slate-950">
              Current Subscription
            </h3>

            <div className="grid gap-5 md:grid-cols-5">

              <div>
                <p className="text-xs text-slate-500">
                  Plan
                </p>

                <p className="mt-1 font-semibold text-slate-950">
                  {formatPlan(
                    subscription.plan
                  )}
                </p>
              </div>

              <div>
                <p className="text-xs text-slate-500">
                  Price
                </p>

                <p className="mt-1 font-semibold text-slate-950">
                  {formatMoney(
                    subscription.amount
                  )}
                  /month
                </p>
              </div>

              <div>
                <p className="text-xs text-slate-500">
                  Status
                </p>

                <p className="mt-1 font-semibold capitalize text-slate-950">
                  {String(
                    subscription.status
                  )}
                </p>
              </div>

              <div>
                <p className="text-xs text-slate-500">
                  Provider
                </p>

                <p className="mt-1 font-semibold text-slate-950">
                  {subscription.provider ||
                    "—"}
                </p>
              </div>

              <div>
                <p className="text-xs text-slate-500">
                  Renewal / Expiry
                </p>

                <p className="mt-1 font-semibold text-slate-950">
                  {formatDate(
                    subscription.renewAt
                  )}
                </p>
              </div>

            </div>

          </div>
        )}

      </div>

      {/* =====================================================
          USERS
          ===================================================== */}

      <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">

        <div className="border-b border-slate-200 p-7">

          <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">

            <div>
              <h2 className="text-2xl font-bold text-slate-950">
                Users
              </h2>

              <p className="mt-1 text-sm text-slate-500">
                Users belonging only to this
                organization.
              </p>
            </div>

            <Link
              href={`/admin/organizations/${id}/users`}
              className="rounded-xl border border-slate-300 px-5 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
            >
              View All Users
            </Link>

          </div>

        </div>

        <div className="overflow-x-auto">

          <table className="w-full min-w-[700px]">

            <thead className="bg-slate-50">

              <tr>

                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  Name
                </th>

                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  Email
                </th>

                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  Role
                </th>

                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  Status
                </th>

              </tr>

            </thead>

            <tbody>

              {organization.users.length ===
              0 ? (
                <tr>
                  <td
                    colSpan={4}
                    className="px-6 py-12 text-center text-sm text-slate-500"
                  >
                    No users assigned to this
                    organization.
                  </td>
                </tr>
              ) : (
                organization.users.map(
                  (user) => (
                    <tr
                      key={user.id}
                      className="border-t border-slate-100"
                    >

                      <td className="px-6 py-5 font-medium text-slate-900">
                        {user.name ||
                          "Unnamed User"}
                      </td>

                      <td className="px-6 py-5 text-sm text-slate-600">
                        {user.email}
                      </td>

                      <td className="px-6 py-5">

                        <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold capitalize text-blue-700">
                          {user
                            .organizationRole
                            ?.name
                            ?.replaceAll(
                              "_",
                              " "
                            ) ??
                            "No Role"}
                        </span>

                      </td>

                      <td className="px-6 py-5">

                        {user.status ===
                        "active" ? (
                          <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-700">
                            Active
                          </span>
                        ) : (
                          <span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-semibold text-orange-700">
                            {user.status}
                          </span>
                        )}

                      </td>

                    </tr>
                  )
                )
              )}

            </tbody>

          </table>

        </div>

      </div>

    </div>
  );
}